# -*- coding: utf-8 -*-
"""Assignment 9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fLdSgLQi4lQ_giOvODK32fO7ZTHQg_qO
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=sns.load_dataset('titanic')
df.head()

sns.boxplot(data=df, x='sex', y='age', hue='survived')

plt.title("Age Distribution by Gender and Survival")
# plt.xlabel("Sex")
# plt.ylabel("Age")

plt.show()

sns.violinplot(data=df, x='sex', y='age', hue='survived')
plt.title("Violin Plot: Age vs Gender with Survival")
plt.show()

df['age_group'] = pd.cut(
    df['age'],
    bins=[0, 12, 18, 30, 50, 80],
    labels=['Child', 'Teen', 'Young Adult', 'Adult', 'Senior']
)

sns.barplot(data=df, x='age_group', y='survived')

plt.title("Survival Rate by Age Group")
plt.ylabel("Survival Probability (0 to 1)")
plt.xlabel("Age Group")

plt.show()

sns.barplot(data=df, x='alone', y='survived')
plt.title("Survival: Alone vs With Family")
# plt.show()
df.head()