# -*- coding: utf-8 -*-
"""Assignment-5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ahQrHOw16cFV4OwXhoVuJgsJm-btSAAV
"""

# Step 1: Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

# Step 2: Social network ads
ads = pd.read_csv('/content/drive/MyDrive/Datasets/Social_Network_Ads.csv')
ads.head()

# Step 3: Initialize the data frame
data = pd.DataFrame(ads)
data.head()

# Step 4: Split dependent variable and independent variables
X = data.drop(['Purchased'], axis=1)
y = data['Purchased']

# Step 5: Train–Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Step 6: Train Logistic Regression model
from sklearn.linear_model import LogisticRegression

# Apply one-hot encoding to the 'Gender' column
X_train_encoded = pd.get_dummies(X_train, columns=['Gender'], drop_first=True)
X_test_encoded = pd.get_dummies(X_test, columns=['Gender'], drop_first=True)

model = LogisticRegression()
model.fit(X_train_encoded, y_train)

# Step 7: Predict test data
y_pred = model.predict(X_test_encoded)

# Step 8: Build Confusion Matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

# Step 9: Compute evaluation metrics

from sklearn.metrics import accuracy_score, precision_score, recall_score

accuracy = accuracy_score(y_test, y_pred)
error_rate = 1 - accuracy
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Error Rate:", error_rate)
print("Precision:", precision)
print("Recall:", recall)