# -*- coding: utf-8 -*-
"""Assignment-6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/187J21xigc_pofvAlSiv0ytBRUfTwjgcq
"""

import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/Iris.csv")

df.head()

df = df.drop("Id", axis=1)

df.isnull().sum()

df['Species'] = df['Species'].astype('category')
df['Species'] = df['Species'].cat.codes

X = df.drop('Species', axis=1)
y = df['Species']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)

from sklearn.naive_bayes import GaussianNB

gaussian = GaussianNB()
gaussian.fit(X_train, y_train)

Y_pred = gaussian.predict(X_test)

from sklearn.metrics import accuracy_score, precision_score, recall_score

accuracy = accuracy_score(y_test, Y_pred)
precision = precision_score(y_test, Y_pred, average='micro')
recall = recall_score(y_test, Y_pred, average='micro')

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, Y_pred)
print(cm)