# -*- coding: utf-8 -*-
"""Assignment-4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KoEbm8U-ROgvW2gplDAnQtNV1HeZc6Dn
"""

'''Create a Linear Regression Model using Python/R to predict
home prices using Boston Housing Dataset .'''

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

boston = pd.read_csv('/content/drive/MyDrive/Datasets/boston.csv')
boston.head()

data = pd.DataFrame(boston)
data.head()

data.isnull().sum()

x = data.drop(['medv'], axis = 1)
y = data['medv']

from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size =0.2, random_state = 0)

import sklearn
from sklearn.linear_model import LinearRegression

lm = LinearRegression()
model = lm.fit(xtrain, ytrain)

ytrain_pred = lm.predict(xtrain)
ytest_pred = lm.predict(xtest)

from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(ytest, ytest_pred)
print(mse)
mse = mean_squared_error(ytrain_pred, ytrain)
print(mse)

plt.scatter(ytrain ,ytrain_pred,c='darkgreen',marker='o',label='Training data')
plt.scatter(ytest,ytest_pred ,c='orange',marker='s',label='Test data')

plt.xlabel('True values')
plt.ylabel('Predicted')
plt.title("True value vs Predicted value")
plt.legend(loc= 'upper left')

plt.plot()
plt.show()