# -*- coding: utf-8 -*-
"""Assignment_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jnGJnR1Djh2BkFAyxtjr7g-NuRW6JoaQ
"""

#1. Provide summary statistics (mean, median, minimum, maximum, standard deviation) for a
#dataset (age, income etc.) with numeric variables grouped by one of the qualitative (categorical)
#variable. For example, if your categorical variable is age groups and quantitative variable is
#income, then provide summary statistics of income grouped bythe age groups. Create a list
#that contains a numeric value for each response to the categorical variable.

import numpy as np
import pandas as pd

df=pd.read_csv('/content/drive/MyDrive/data.csv')
df.head()

grouped_stats = df.groupby("gender")["income"].agg(
    mean="mean",
    median="median",
    minimum="min",
    maximum="max",
    std_dev="std"
)

grouped_stats

income_list_by_gender = df.groupby("gender")["income"].apply(list)

income_list_by_gender

# 2.Write a Python program to display some basic statistical details like percentile, mean, standard
#deviation etc. of the species of ‘Iris-setosa’, ‘Iris-versicolor’ and ‘Iris- versicolor’ of iris.csv
#dataset.

iris = pd.read_csv("/content/drive/MyDrive/Iris.csv")
iris.head()

print(iris.columns)

iris_stats = iris.groupby("Species").describe()
iris_stats

for species in iris["Species"].unique():
    print(f"\nStatistics for {species}")

    subset = iris[iris["Species"] == species]

    print("Mean:\n", subset.mean(numeric_only=True))
    print("\nStandard Deviation:\n", subset.std(numeric_only=True))
    print("\nPercentiles:\n", subset.quantile([0.25, 0.50, 0.75], numeric_only=True))