# -*- coding: utf-8 -*-
"""Assugnment 8 DSBDL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1InzEClW2K2xj4O1jfC2f7G5BK3PcYXil
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=sns.load_dataset('titanic')
df.head()

df.info()

sns.histplot(df['age'],kde=True)
plt.title('age distribution')
plt.show()

sns.countplot(x='survived', data=df)
plt.title("Survival Count")
plt.show()

sns.countplot(x='sex', hue='survived', data=df)
plt.title("Survival by Gender")
plt.show()

sns.barplot(x='pclass', y='survived', data=df)
plt.title("Survival Rate by Class")
plt.show()

sns.boxplot(x='pclass', y='fare', data=df)
plt.title("Fare Distribution by Class")
plt.show()

sns.violinplot(x='sex', y='age', data=df)
plt.title("Age Distribution by Gender")
plt.show()

sns.histplot(data=df, x='fare', bins=30, kde=True)

plt.title("Distribution of Ticket Fare")
plt.xlabel("Fare")
plt.ylabel("Number of Passengers")

plt.show()