# -*- coding: utf-8 -*-
"""P1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1np6qzbeUDI1Brxg9cBlHMe_XtBiLmjzX
"""

import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/Iris.csv")

df.head()

df.isnull().sum()

df.describe()

df.shape

df.dtypes

df.drop(columns=['Id'], inplace=True)

df.rename(columns={
    'SepalLengthCm':'sepal_length',
    'SepalWidthCm':'sepal_width',
    'PetalLengthCm':'petal_length',
    'PetalWidthCm':'petal_width',
    'Species':'species'
}, inplace=True)

df['species'] = df['species'].astype('category')

df.dtypes

scaler = MinMaxScaler()
df[['sepal_length','sepal_width','petal_length','petal_width']] = scaler.fit_transform(
    df[['sepal_length','sepal_width','petal_length','petal_width']]
)

le = LabelEncoder()
df['species_encoded'] = le.fit_transform(df['species'])

df.head()