# -*- coding: utf-8 -*-
"""P2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gb25GJ0bX0JhHAxnF7I8W_R23dzUUHx2
"""

import pandas as pd
import numpy as np

df=pd.read_csv("/content/drive/MyDrive/DSBDL/Acedemic Performance.csv")

df.tail()

df.isnull().sum()

df.isna().sum().sum()

df.loc[df["mathsscore"] > 100, "mathsscore"] = np.nan
df.loc[df["readingscore"] > 100, "readingscore"] = np.nan
df.loc[df["writingscore"] > 100, "writingscore"] = np.nan
df.loc[df["placementscore"] > 100, "placementscore"] = np.nan

df["writingscore"] = df["writingscore"].fillna(df["writingscore"].median())

df.isna().sum()

df["placementscore"] = df["placementscore"].fillna(df["placementscore"].median())

df.isnull().sum()

df["mathsscore"] = df["mathsscore"].fillna(df["mathsscore"].median())
df["readingscore"] = df["readingscore"].fillna(df["readingscore"].median())

df.isnull().sum().sum()

numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print(f"\nColumn: {col}")
    print("Lower Bound:", lower)
    print("Upper Bound:", upper)
    print("Outliers Found:", len(outliers))

df["placementscore"].skew()

df["placementscore_1to10"] = (df["placementscore"] / 10).round(0)

df.head()

import matplotlib.pyplot as plt

avg_scores = df[["mathsscore","readingscore","writingscore","placementscore"]].mean()

avg_scores.plot(kind="bar")

plt.title("Average Scores of Subjects")
plt.ylabel("Average Score")
plt.show()