# -*- coding: utf-8 -*-
"""Practicle 10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tA4x1sT0futJhMqsDBl-JkRzlFQsn931
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/Iris.csv")

print(df.dtypes)

df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']].hist(figsize=(10,8))
plt.suptitle("Histograms of Iris Dataset")
plt.show()

plt.figure(figsize=(10, 6))

for i, column in enumerate(df.columns[1:-1], 1):  # exclude 'Id' and 'Species' columns
    plt.subplot(2, 2, i)
    sns.boxplot(y=df[column])
    plt.title(column)

plt.tight_layout()
plt.show()

# Using IQR method to detect outliers

for col in df.columns[:-1]:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print(f"{col}: {len(outliers)} outliers")